name: ci

on:
  push:
    branches:
      - disser

jobs:
  build:
    runs-on: ubuntu-latest
    container: raabf/texstudio-versions
    steps:
      - uses: actions/checkout@v3
      - run: dockertex --tag texlive2016 pdftexreport report.tex