name: ci

on:
  push:
    branches:
      - disser

jobs:
  build:
    runs-on: ubuntu-latest
    container: raabf/latex-versions:texlive2016
    steps:
      - uses: actions/checkout@v3
      - run: latexmk -pdf -pdflatex="xelatex %O %S" synopsis
      - run: latexmk -pdf -pdflatex="xelatex %O %S" report
      - uses: actions/upload-artifact@v3
        with:
          name: my-disser
          path: |
            synopsis.pdf
            report.pdf